from tkinter import *
from typing import Sized
root = Tk()
#Maintain Debtors
Tittle = Label(text="Debtors Master")
Tittle.grid(row=0,column=1,padx=10,pady=10)
accountCode = Label(text="Account code")
accountCode.grid(row=1, column=0,padx=10,pady=10)
a = Entry()
a.get()
a.grid(row=1,column=1,columnspan=3,padx=10,pady=10)
Address1 = Label(text="Address 1")
Address1.grid(row=2, column=0,padx=10,pady=10)
b = Entry()
b.get()
b.grid(row=2,column=1,columnspan=3,padx=10,pady=10)
Address2 = Label(text="Address2")
Address2.grid(row=3, column=0,padx=10,pady=10)
c = Entry()
c.get()
c.grid(row=3,column=1,columnspan=3,padx=10,pady=10)
Address3 = Label(text="Address3")
Address3.grid(row=4, column=0,padx=10,pady=10)
d = Entry()
d.get()
d.grid(row=4,column=1,columnspan=3,padx=10,pady=10)
Balance = Label(text="Balance")
Balance.grid(row=5,column=0,padx=10,pady=10)
e = Entry()
e.get()
e.grid(row=5,column=1,columnspan=3,padx=10,pady=10)
SalesYearToDate = Label(text="Sales Year to date")
f = Entry()
f.get()
f.grid(row=6,column=1,columnspan=3,padx=10,pady=10)
SalesYearToDate.grid(row=6, column=0,padx=10,pady=10)
CostYearToDate = Label(text="Cost of the year")
CostYearToDate.grid(row=7, column=0,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=7,column=1,columnspan=3,padx=10,pady=10)

#Debtors transaction file
Tittle0 = Label(text="\t")
Tittle0.grid(row=8,column=1,padx=10,pady=10)
Tittle1= Label(text="Debtors transaction file")
Tittle1.grid(row=9,column=1,padx=10,pady=10)
Acc = Label(text="Account code")
Acc.grid(row=10, column=0,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=10,column=1,columnspan=3,padx=10,pady=10)
Date = Label(text="Date")
Date.grid(row=11, column=0,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=11,column=1,columnspan=3,padx=10,pady=10)
TransactionType = Label(text="Transaction type")
TransactionType.grid(row=12, column=0,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=12,column=1,columnspan=3,padx=10,pady=10)
DocumentNo= Label(text="Document No")
DocumentNo.grid(row=13, column=0,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=13,column=1,columnspan=3,padx=10,pady=10)
GrossTransactionValue = Label(text="Gross Transaction Value")
GrossTransactionValue.grid(row=14, column=0,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=14,column=1,columnspan=3,padx=10,pady=10)
Vat_Value = Label(text="Vat Value")
Vat_Value.grid(row=15, column=0,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=15,column=1,columnspan=3)
#Stack Master file
Tittle2 = Label(text="\t")
Tittle2.grid(row=16,column=1,padx=10,pady=10)
Tittle1= Label(text="Stock Master File")
Tittle1.grid(row=17,column=1,padx=10,pady=10)
stock_code= Label(text="Stock Code")
stock_code.grid(row=18, column=0,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=18,column=1,columnspan=3)
stock_Description = Label(text="Stock Description")
stock_Description.grid(row=19, column=0,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=19,column=1,columnspan=3,padx=10,pady=10)
cost= Label(text="cost")
cost.grid(row=10, column=5,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=10,column=6,columnspan=3,padx=10,pady=10)
SellPrice= Label(text="selling price")
SellPrice.grid(row=11, column=5,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=11,column=6,columnspan=3,padx=10,pady=10)
PriceExclVat= Label(text="Total Purchases Excl Vat")
PriceExclVat.grid(row=12, column=5,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=12,column=6,columnspan=3,padx=10,pady=10)
TotalSale= Label(text="Total Sales Excl Vat")
TotalSale.grid(row=13, column=5,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=13,column=6,columnspan=3,padx=10,pady=10)
Qty= Label(text="Qty Purchsed")
Qty.grid(row=14, column=5,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=14,column=6,columnspan=3,padx=10,pady=10)
QtySold= Label(text="Qty Sold")
QtySold.grid(row=15, column=5,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=15,column=6,columnspan=3,padx=10,pady=10)
'''StockOnHand= Label(text="Stock On hand")
StockOnHand.grid(row=10, column=13,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=10,column=14,columnspan=3,padx=10,pady=10)'''
#Stock Transaction File
Tittle2 = Label(text="\t")
Tittle2.grid(row=0,column=4,padx=10,pady=10)
Tittle1= Label(text="Stock Transaction File")
Tittle1.grid(row=0,column=5,padx=10,pady=10)
StockCode= Label(text="Stock code")
StockCode.grid(row=1, column=4,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=1,column=5,columnspan=3,padx=10,pady=10)
date= Label(text="Date")
date.grid(row=2, column=4,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=2,column=5,columnspan=3,padx=10,pady=10)
TransType= Label(text="Transaction Type")
TransType.grid(row=3, column=4,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=3,column=5,columnspan=3,padx=10,pady=10)
DocNo= Label(text="Document Number")
DocNo.grid(row=4, column=4,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=4,column=5,columnspan=3,padx=10,pady=10)
qty1= Label(text="Qty")
qty1.grid(row=5, column=4,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=5,column=5,columnspan=3,padx=10,pady=10)
UnitCost= Label(text="Unit Cost")
UnitCost.grid(row=6, column=4,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=6,column=5,columnspan=3,padx=10,pady=10)
UnitSell= Label(text="Unit sell")
UnitSell.grid(row=7, column=4,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=7,column=5,columnspan=3,padx=10,pady=10)
#Invoce Header 
Tittle2 = Label(text="\t")
Tittle2.grid(row=0,column=10,padx=10,pady=10)
Tittle1= Label(text="Invoice Header")
Tittle1.grid(row=0,column=10,padx=10,pady=10)
InvoiceNo= Label(text="Invoice No")
InvoiceNo.grid(row=1, column=8,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=1,column=9,columnspan=3,padx=10,pady=10)
Accountcode1= Label(text="Account Code")
Accountcode1.grid(row=2, column=8,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=2,column=9,columnspan=3,padx=10,pady=10)
Date1= Label(text="Date")
Date1.grid(row=3, column=8,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=3,column=9,columnspan=3,padx=10,pady=10)
TotalSell= Label(text="Total Sell Amount Exl VAT")
TotalSale.grid(row=4, column=8,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=4,column=9,columnspan=3,padx=10,pady=10)
VAT1= Label(text="VAT")
VAT1.grid(row=1, column=8,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=1,column=9,columnspan=3,padx=10,pady=10)
TotalCost= Label(text="Total Cost")
TotalCost.grid(row=1, column=8,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=1,column=9,columnspan=3,padx=10,pady=10)
#Invoice Detail
Tittle2 = Label(text="\t")
Tittle2.grid(row=9,column=11,padx=10,pady=10)
Tittle1= Label(text="Invoice Detail")
Tittle1.grid(row=9,column=11,padx=10,pady=10)
InvoiceNo1= Label(text="Invoice No")
InvoiceNo1.grid(row=10, column=10,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=10,column=11,columnspan=3,padx=10,pady=10)
ItemNo1= Label(text="Item No")
ItemNo1.grid(row=11, column=10,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=11,column=11,columnspan=3,padx=10,pady=10)
StockCode1= Label(text="Stock code")
StockCode1.grid(row=12, column=10,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=12,column=11,columnspan=3,padx=10,pady=10)
Qty1= Label(text="Qty Sold")
Qty1.grid(row=13, column=10,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=13,column=11,columnspan=3,padx=10,pady=10)
Unit1= Label(text="unit Cost")
Unit1.grid(row=14, column=10,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=14,column=11,columnspan=3,padx=10,pady=10)
UnitSell1= Label(text="Unit Sell")
UnitSell1.grid(row=15, column=10,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=15,column=11,columnspan=3,padx=10,pady=10)
Disc= Label(text="Disc")
Disc.grid(row=1, column=12,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=1,column=13,columnspan=3,padx=10,pady=10)
Total= Label(text="Total")
Total.grid(row=2, column=12,padx=10,pady=10)
g = Entry()
g.get()
g.grid(row=2,column=13,columnspan=3,padx=10,pady=10)


root.mainloop()
